# 将项目构建镜像并发布至 Docker Hub
name: CI to Docker Hub

# 在 Push 到 main 分支后启动该流程
on:
  schedule:
    - cron:  '30 8 * * 6'

  workflow_dispatch:

#  push:
#    branches:
#      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 在 GitHub Action 的服务器上 Check Out 源码（整体流程结束后会重置服务器环境因此不需要担心泄露）
      - name: Check Out Repo 
        uses: actions/checkout@v3
      # 登录至 Docker Hub，账户密码需要在 Settings -> Secrets 中设置
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # 设置 Buildx 为构建镜像做准备
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      # 构建并发布（执行项目路径下的 Dockerfile 文件）
      - name: Build ubuntu20.04:latest and push
        id: latest
        uses: docker/build-push-action@v2
        with:
          context: ./Ubuntu-20.04
          file: ./Ubuntu-20.04/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ubuntu20.04:latest

      # 完成
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
